"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$cmd_duration"

add_newline = false

[character]
success_symbol = "[➜](bold #bd93f9) "
error_symbol = "[➜](bold #ff5555) "

[hostname]
ssh_only = false
format = "[$hostname](bold #bd93f9) "
disabled = false

[cmd_duration]
min_time = 1
format = "[$duration](bold #bd93f9)"

[directory]
truncation_length = 5
truncation_symbol = "/"

[git_branch]
symbol = "-"
truncation_length = 4
truncation_symbol = ""

[git_status]
format = ""

[java]
symbol = "[](bold #ff5555) "

[nodejs]
symbol = "[](bold #f1fa8c) "

[ruby]
symbol = "[](bold #ff5555) "

[python]
symbol = "[](bold 	#50fa7b) "
